[[cells]]
name = "hackathon"
enable_type_id = true
location = { file = "build/release/hackathon" }

# # Dep group cells
# [[dep_groups]]
# name = "my_dep_group"
# cells = [
#   "my_cell",
#   "secp256k1_data"
# ]

# # Replace with your own lock if you want to unlock deployed cells.
# # The deployment code_hash is secp256k1 lock
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0xd310bba5375bda7a2ace4f9a483bd51d12384bd1"
hash_type = "type"
